spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      
logging:
  level:
    org.springframework.web: DEBUG
    com.phorest: DEBUG
    org.hibernate: INFO

